[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "01Variables"
path = "src/01Variables.rs"

[[bin]]
name = "02ConditionalLoops"
path = "src/02ConditionalLoops.rs"